# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iUX46KspcGRI-yxSdwfSaZR35CNfGE-
"""

# API Simples
# instalação de pacotes - flask 
!pip install flask
!pip install flask-ngrok
!pip install fastapi nest-asyncio pyngrok uvicorn

# Criando rota
from fastapi import FastAPI
import nest_asyncio
from pyngrok import ngrok
import uvicorn
from flask import Flask, jsonify
import pandas as pd

app = Flask(__name__)

@app.route('/index')
def home():
  data = pd.read_json('arquivo.json')
  data_dict = data.to_dict()
  return jsonify(data_dict)

if __name__ == '__main__':
    app.run()