# -*- coding: utf-8 -*-
"""image-processing-package

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i5iGHf27wNgVpClakSmUJT3RHcVDdAOf
"""

image-processing-package/
  README.md
  setup.py
  requirements.txt
  image_processing/
    __init__.py
    processing/
      __init__.py
      combination.py
      transformation.py
    utils/
      __init__.py
      io.py
      plot.py