# -*- coding: utf-8 -*-
"""Projeto_DIO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i5iGHf27wNgVpClakSmUJT3RHcVDdAOf
"""

projeto_DIO/
  README.md
  setup.py
  requirements.txt
  projeto_DIO/
    __init__.py
    modulo1/
      __init__.py
      arquivo1.py
      arquivo2.py
    modulo2/
      __init__.py
      arquivo1.py
      arquivo2.py